baseURL = 'https://abigailswallow.com/'
languageCode = 'en-us'
title = 'Abigail Swallow'
theme = "tailwind"
copyright = "2022-{year} Abigail Swallow. All rights reserved."

pluralizeListTitles = false

[params]
    name = "Abigail Swallow's Portfolio"
    description = "A website featuring Abigail Swallow's work, bio and ideas."

    favicon = "/static/imgs/favicons/favicon.ico"

[markup.goldmark.renderer]
unsafe = true
